### ISSUE TITLE
dragging selection to extreme right edge sometimes falls 1px short

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/uPlot#123]
e.g. seems to affect some charts at devicePixelRatio 1.0.

in the mouseup handler, the right edge is 1px short of the full range. both in FF and Chrome.

removing this solves it for some reason:

```css
.uplot .plot {
  outline: 1px solid #eee;
}
```

it's possible to add a hack that assumes if it's 1px from right, then snap it, but would be good to figure out what's actually going on.
