### ISSUE TITLE
Move legend to left (and stack)

### ISSUE THREAD

**Issue by jmthomas** [leeoniya/uPlot#704]
I followed your basic code in #398 to create the following method in my Vue.js app:
```
    moveLegend: function (desired) {
      if (desired === this.legendPosition) {
        return
      }
      let legendEl = this.graph.root.querySelector('.u-legend')
      let wrapEl = this.graph.root.querySelector('.u-wrap')
      switch (desired) {
        case 'bottom':
          wrapEl.parentNode.insertBefore(legendEl, wrapEl.nextSibling)
          this.legendPosition = 'bottom'
          break
        case 'top':
          this.graph.root.insertBefore(legendEl, wrapEl)
          this.legendPosition = 'top'
          break
        case 'left':
          # ????
          this.legendPosition = 'left'
          break
      }
    },
```
This moves the legend back and forth from top to bottom very neatly. However I'm not sure what to do with moving it to the left (or right). Also how would I stack the values as that would make sense moving left or right.

**Comment by leeoniya** [comment]
you can actually do this with just CSS overrides: https://jsfiddle.net/rntm0qwp/

![image](https://user-images.githubusercontent.com/43234/172466404-d9f46c64-0a58-454b-b022-017957f1934c.png)

```css
/* right/stacked legend */
.uplot.rgt-leg {
  display: flex;
  width: auto;
}

.uplot.rgt-leg .u-wrap {
  flex: none;
}

.uplot.rgt-leg .u-legend {
  text-align: left;
  margin-left: 0;
}

.uplot.rgt-leg .u-legend,
.uplot.rgt-leg .u-legend tr,
.uplot.rgt-leg .u-legend th,
.uplot.rgt-leg .u-legend td {
  display: revert;
}


/* top legend */
.uplot.top-leg {
  display: flex;
  flex-direction: column;
}

.uplot.top-leg .u-legend {
  order: -1;
}
```

```js
  hooks: {
    init: [
      u => {
        u.root.classList.add('rgt-leg');
        //u.root.classList.add('top-leg');
      }
    ]
  },
```
