### ISSUE TITLE
try css transforms for selection sizing

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/uPlot#781]
should be better perf than manipulating left/width and top/height.

also, can set `width: 1px; translateX(250px)` at initial start and then only use neg or pos scaleX to set width instead of inverting them when selection goes the other way.

```css
.u-select {
  position: absolute;
  background: pink;
  height: 600px;
  transform-origin: 0 0;

  width: 1px;
  transform: translateX(250px) scaleX(-100);
}
```
